export const languages = [
  { name: "Arabic", value: "ar" },
  { name: "Chinese", value: "zh" },
  { name: "Dutch", value: "nl" },
  { name: "English", value: "en" },
  { name: "Finnish", value: "fi" },
  { name: "French", value: "fr" },
  { name: "German", value: "de" },
  { name: "Hindi", value: "hi" },
  { name: "Italian", value: "it" },
  { name: "Japanese", value: "ja" },
  { name: "Korean", value: "ko" },
  { name: "Malay", value: "msa" },
  { name: "Portuguese", value: "pt" },
  { name: "Russian", value: "ru" },
  { name: "Spanish", value: "es" },
  { name: "Vietnamise", value: "vi" },
  { name: "Danish", value: "da" },
  { name: "Czech", value: "cs" },
  { name: "Greek", value: "el" },
  { name: "Hungarian", value: "hu" },
  { name: "Serbian", value: "sr" },
  { name: "Turkish", value: "tr" },
];

export const regions = [
  { name: "United State", value: "US" },
  { name: "Taiwan", value: "TW" },
  { name: "German", value: "DE" },
  { name: "United Kingdom", value: "GB" },
  { name: "China", value: "CN" },
  { name: "India", value: "IN" },
  { name: "Spain", value: "ES" },
  { name: "Italy", value: "IT" },
  { name: "Poland", value: "PL" },
  { name: "Australia", value: "AU" },
  { name: "Malaysia", value: "MY" },
  { name: "Singapore", value: "SG" },
  { name: "Canada", value: "CA" },
  { name: "South Korea", value: "KR" },
  { name: "Denmark", value: "DK" },
  { name: "France", value: "FR" },
  { name: "Belgium", value: "BE" },
  { name: "Japan", value: "JP" },
  { name: "Austria", value: "AT" },
  { name: "Portugal", value: "PT" },
  { name: "Philippines", value: "PH" },
  { name: "Hong Kong", value: "HK" },
  { name: "Argentina", value: "AR" },
  { name: "Venezuela", value: "VE" },
  { name: "Brazil", value: "BR" },
  { name: "Finland", value: "FI" },
  { name: "Indonesia", value: "ID" },
  { name: "Vietnam", value: "VN" },
  { name: "Mexico", value: "MX" },
  { name: "Greece", value: "GR" },
  { name: "Netherlands", value: "NL" },
  { name: "Norway", value: "NO" },
  { name: "New Zealand", value: "NZ" },
  { name: "Russia", value: "RU" },
  { name: "Saudi-Arabia", value: "SA" },
  { name: "Switzerland", value: "CH" },
  { name: "Thailand", value: "TH" },
  { name: "United Arab Emirates", value: "AE" },
  { name: "Ireland", value: "IE" },
  { name: "Iran", value: "IR" },
  { name: "Iraq", value: "IQ" },
  { name: "Romania", value: "RO" },
  { name: "Afghanistan", value: "AF" },
  { name: "Zimbabwe", value: "ZW" },
  { name: "Myanmar", value: "MM" },
  { name: "Sweden", value: "SE" },
  { name: "Peru", value: "PE" },
  { name: "Panama", value: "PA" },
  { name: "Egypt", value: "EG" },
  { name: "Turkey", value: "TR" },
  { name: "Israel", value: "IL" },
  { name: "Czech Republic", value: "CZ" },
  { name: "Bangladesh", value: "BD" },
  { name: "Nigeria", value: "NG" },
  { name: "Kenya", value: "KE" },
  { name: "Chile", value: "CL" },
  { name: "Uruguay", value: "UY" },
  { name: "Ecuador", value: "EC" },
  { name: "Serbia", value: "RS" },
  { name: "Hungary", value: "HU" },
  { name: "Slovenia", value: "SI" },
  { name: "Ghana", value: "GH" },
  { name: "Bolivia", value: "BO" },
  { name: "Pakistan", value: "PK" },
  { name: "Colombia", value: "CO" },
  { name: "North Korea", value: "NK" },
  { name: "Paraguay", value: "PY" },
  { name: "Palestine", value: "PS" },
  { name: "Estonia", value: "EE" },
  { name: "Lebanon", value: "LB" },
  { name: "Qatar", value: "QA" },
  { name: "Kuwait", value: "KW" },
  { name: "Cambodia", value: "KH" },
  { name: "Nepal", value: "NP" },
  { name: "Luxembourg", value: "LU" },
  { name: "Bosnia", value: "BA" },
  { name: "Europe", value: "EU" },
  { name: "Asia", value: "ASIA" },
  { name: "International", value: "INT" },
];

export const categories = [
  "regional",
  "technology",
  "lifestyle",
  "business",
  "general",
  "programming",
  "science",
  "entertainment",
  "world",
  "sports",
  "finance",
  "academia",
  "politics",
  "health",
  "opinion",
  "food",
  "game",
  "fashion",
  "academic",
  "crap",
  "travel",
  "culture",
  "economy",
  "environment",
  "art",
  "music",
  "notsure",
  "CS",
  "education",
  "redundant",
  "television",
  "commodity",
  "movie",
  "entrepreneur",
  "review",
  "auto",
  "energy",
  "celebrity",
  "medical",
  "gadgets",
  "design",
  "EE",
  "security",
  "mobile",
  "estate",
  "funny",
];
